//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34209
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections;
using UnityEngine;
using UnityEngine.EventSystems;

public class UIProductionMenuClass : UIObjectClass//, IPointerDownHandler
{

//	delegate void MenuPanelDelegate();
//	delegate void facilityPanelDelegate();
//
//	MenuPanelDelegate m_menuPanelMethod;
//	facilityPanelDelegate facilityPanelMethod;

//	[SerializeField] UIEmployeeClass m_employeePanel;
//	[SerializeField] UIFacilityClass m_facilityPanel;

	UIProductionLineClass m_productionLine;









	public void setMenuPanel(UIProductionLineClass productionLine){
		//메뉴창 초기화
		UIMadiatorClass.UIEffectSoundPlayer(TYPE_AUDIO.NONE);

		m_productionLine = productionLine;
//		employPanelMethod = m_productionLine.employeePanelView;
//		facilityPanelMethod = m_productionLine.facilityPanelView;
		gameObject.SetActive (true);
	}

//	public void OnPointerDown( PointerEventData eventData ){
//		Debug.Log ("마우스 다운");
//	}

	public void employeeBtnClicked(){
		//직원창 띄우기
		Debug.Log ("employee");
//		employPanelMethod ();

		menuPanelClose ();
		UIMadiatorClass.UIEmployeePanelView(this, m_productionLine.employeeCase.employee, TYPE_PANEL.NONE, m_productionLine.usePos);

//		m_employeePanel.gameObject.SetActive (true);
//		m_employeePanel.setEmployeePanel (m_productionLine.employeeCase.employee);
	}

	public void facilityBtnClicked(){
		//시설창 띄우기
		Debug.Log ("facility");
//		facilityPanelMethod ();

		menuPanelClose ();
		UIMadiatorClass.UIFacilityPanelView(this, m_productionLine.facilityCase.facility, TYPE_PANEL.NONE, m_productionLine.usePos);
//		m_facilityPanel.gameObject.SetActive (true);
//		m_facilityPanel.setFacilityPanel ();
	}

	public void menuPanelClose(){
		UIMadiatorClass.UIEffectSoundPlayer(TYPE_AUDIO.NONE);
		panelClose ();
	}

}


