//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34209
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections;
using System.Collections.Generic;
public class TranslatorClass : SingletonClass<TranslatorClass>
{
	public TranslatorClass(){
		initParse ();
	}

	private void initParse(){
		//번역기 파싱
		//해당 데이터와 번역기로 출력
		//한글, 영어 등
	}

	/// <summary>
	/// 시설 종류 번역
	/// </summary>
	/// <returns>The facility word.</returns>
	/// <param name="facilityType">Facility type.</param>
	public string getFacilityWord(TYPE_FACILITY facilityType){
		switch (facilityType) {
		case TYPE_FACILITY.PRODUCT:
			return "생산";
		case TYPE_FACILITY.MANUFACTURE:
			return "제조";
		case TYPE_FACILITY.BUSINESS:
			return "판매";
		case TYPE_FACILITY.RESEARCH:
			return "연구";
		case TYPE_FACILITY.NONE:
			return "전체";
		}
		return "-";
	}

	/// <summary>
	/// 뷰 종류 번역
	/// </summary>
	/// <returns>The facility word.</returns>
	/// <param name="facilityType">Facility type.</param>
	public string getViewWord(TYPE_VIEW viewType){
		switch (viewType) {
		case TYPE_VIEW.EMPLOYEE:
			return "직원";
		case TYPE_VIEW.FACILITY:
			return "시설";
		}
		return "-";
	}

	/// <summary>
	/// 캐릭터 성격 번역
	/// </summary>
	/// <returns>The character word.</returns>
	/// <param name="characterType">Character type.</param>
	public string getCharacterWord(TYPE_CHARACTER characterType){
		switch (characterType) {
		case TYPE_CHARACTER.ANGER:
			return "분노";
		case TYPE_CHARACTER.CHARISMA:
			return "카리스마";
		case TYPE_CHARACTER.BRAINY:
			return "총명";
		case TYPE_CHARACTER.CHEERFUL:
			return "명랑";
		case TYPE_CHARACTER.FAST:
			return "신속";
		case TYPE_CHARACTER.HEALTY:
			return "건강";
		case TYPE_CHARACTER.NONE:
			return "평범";
		case TYPE_CHARACTER.SINCERITY:
			return "성실";
		case TYPE_CHARACTER.TIMID:
			return "소심";
		case TYPE_CHARACTER.WARMBLOODED:
			return "열혈";
		}
		return "-";
	}

	/// <summary>
	/// 회사 등급 번역
	/// </summary>
	/// <returns>The company grade.</returns>
	/// <param name="grade">Grade.</param>
	public string getCompanyGrade(TYPE_GRADE grade){
		switch (grade) {
		case TYPE_GRADE.STARTUP:
			return "스타트업";
		case TYPE_GRADE.SOHO:
			return "소호";
		case TYPE_GRADE.SMALL:
			return "중소기업";
		case TYPE_GRADE.MID:
			return "중견기업";
		case TYPE_GRADE.COPER:
			return "대기업";

		}
		return "-";
	}

	/// <summary>
	/// 직급 번역
	/// </summary>
	/// <returns>The rank.</returns>
	/// <param name="rank">Rank.</param>
	public string getRank(TYPE_RANK rank){
		switch (rank) {
		case TYPE_RANK.INTERN:
			return "인턴";
		case TYPE_RANK.MEMBER:
			return "사원";
		case TYPE_RANK.ASSOCIATE:
			return "주임";
		case TYPE_RANK.ASSOCIATE_MANAGER:
			return "대리";
		case TYPE_RANK.MANAGER:
			return "과장";
		case TYPE_RANK.TEAM_MANAGER:
			return "팀장";
		case TYPE_RANK.DEPARTMENT_MANAGER:
			return "부장";
		case TYPE_RANK.DIRECTOR:
			return "실장";
		case TYPE_RANK.MANAGING_DIRECTOR:
			return "상무";
		case TYPE_RANK.SENIOR_MANAGING_DIRECTOR:
			return "전무";
		}
		return "-";
	}


}


