//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.36373
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using UnityEngine;

public enum TYPE_BGM{
	MAIN,
	PLAY,
	FEVER
}


public class UIBGMSoundClass : MonoBehaviour
{
	AudioClip[] m_audios = new AudioClip[Enum.GetValues(typeof(TYPE_BGM)).Length];
	AudioSource m_audioSource;


	void Start(){
		m_audioSource = GetComponent<AudioSource> ();
		m_audioSource.loop = true;
		m_audioSource.playOnAwake = true;
		BGMMute ();
		
		DontDestroyOnLoad (this);
	}

	/// <summary>
	/// 배경음 설정하기
	/// </summary>
	/// <returns><c>true</c>, if effect sound was set, <c>false</c> otherwise.</returns>
	public bool setBGMSound(AssetBundle bundle){
		for(int i = 0; i < Enum.GetValues(typeof(TYPE_BGM)).Length; i++){
			try{
				string type = string.Format("{0}_{1}BGM", i, (TYPE_BGM)i);
				Debug.Log("BGM Type : " + type);
				m_audios[i] = bundle.LoadAsset<AudioClip>(type);
			}
			catch(UnityException e){
				Debug.LogError("배경 사운드 불러오기 오류 : " + e.Message);
			}
		}
		
		return true;
	}

	/// <summary>
	/// 배경음 플레이
	/// </summary>
	/// <param name="bgm">Bgm.</param>
	public void BGMPlay(TYPE_BGM bgm){
		m_audioSource.clip = m_audios [(int)bgm];
		BGMMute ();
		m_audioSource.Play ();
	}

	/// <summary>
	/// 배경음 페이드 플레이
	/// </summary>
	/// <param name="bgm">Bgm.</param>
	public void BGMPadePlay(TYPE_BGM bgm){

	}

	/// <summary>
	/// 배경음 뮤트
	/// </summary>
	public void BGMMute(){
		m_audioSource.mute = (PlayerPrefs.GetInt ("isBackgroundSound", 0) == 1) ? true : false;
	}

	/// <summary>
	/// 배경음 정지
	/// </summary>
	public void BGMStop(){
		m_audioSource.Stop ();
	}


}

