//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.36373
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.Events;
public class UICashSummaryClass : UIObjectClass
{
	//이름
	//획득 주화
	//판매 가격
	//종류

	enum TYPE_CASH{PINECOLA, ASSET}



	[SerializeField] Image m_iconImage;
	[SerializeField] Sprite[] m_images;
	[SerializeField] string[] m_data;
	[SerializeField] Text m_nameText;
	[SerializeField] Text m_costText;
	[SerializeField] TYPE_CASH m_cashType;

	int useAsset;
	int getAsset;

	void Awake(){
		GetComponent<Button> ().onClick.AddListener (new UnityAction (msgBoxView));
	}

	public int indexCount{get{return m_data.Length;}}

	public bool setData(int index){
		if (index < m_data.Length) {
			string[] tmpdata = m_data[index].Split('-');
			useAsset = int.Parse(tmpdata[1]);
			getAsset = int.Parse(tmpdata[0]);

			switch(m_cashType){
			case TYPE_CASH.ASSET:
				m_nameText.text = string.Format("{0}원", getAsset);
				m_costText.text = string.Format("{0}", useAsset);
				break;
			case TYPE_CASH.PINECOLA:
				m_nameText.text = string.Format("{0}파인콜라", getAsset);
				m_costText.text =  string.Format("{0}", useAsset);
				break;
			}
			m_iconImage.sprite = m_images[index];
			return true;
		}
		return false;
	}

	public void msgBoxView(){
		//구입하시겠습니까?
		UIMadiatorClass.UIEffectSoundPlayer(TYPE_AUDIO.NONE);

		UIMadiatorClass.UIMsgPanelView.initMsgPanel("구입하시겠습니까?", costData, TYPE_MSG_SIGN.OKCANCEL);
//		switch(m_cashType){
//		case TYPE_CASH.ASSET:
//			//캐시가 부족합니다. 캐시를 구입하시겠습니까?
//			break;
//		case TYPE_CASH.PINECOLA:
//			
//			break;
//		}
//		costData ();
	}

	private void costData(){
		switch(m_cashType){
		case TYPE_CASH.ASSET:
			if(AccountClass.GetInstance.pinecola < useAsset){
				effectSoundPlayer(TYPE_AUDIO.WARNING);
				UIMadiatorClass.UIMsgPanelView.initMsgPanel("파인콜라가 부족합니다.", TYPE_MSG_ICON.ERROR);
			}
			else{
				effectSoundPlayer(TYPE_AUDIO.COST);
				AccountClass.GetInstance.usePineCola(useAsset);
				AccountClass.GetInstance.addAssets(getAsset, TYPE_FINANCE.SUBSIDY);
				UIMadiatorClass.UIMsgPanelView.initMsgPanel("구입 완료", TYPE_MSG_ICON.INFOR);
			}
			break;
		case TYPE_CASH.PINECOLA:
			//결재 정보 필요
			effectSoundPlayer(TYPE_AUDIO.COST);
			AccountClass.GetInstance.addPineCola(getAsset);
			UIMadiatorClass.UIMsgPanelView.initMsgPanel("구입 완료", TYPE_MSG_ICON.INFOR);
			break;
		}
		//구입 완료
	}



}


