//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.36373
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;

public class UIFeverTimeClass : MonoBehaviour
{

	Animator m_animator;

	void Start(){
		m_animator = GetComponent<Animator> ();
		m_animator.speed = getTime ();
	}


	private float getTime(){
		return Random.Range(0.5f, 1.5f);
	}


	private void endAnimation(){
		m_animator.speed = getTime ();
	}
}


