//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.36373
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.Events;


enum TYPE_FINAN_PANEL{NONE, SAVE, LOAN, STOCK}

public class UIFinanceClass : UIObjectClass
{

	//수입 및 지출
	//시설 유지비
	//직원 급여
	//직원 고용
	//연구 비용
	//금리
	//지원금
	//수익
	//회사 가치
	
	[SerializeField] UIFinanceSubClass m_financeSubPanel;
	//[SerializeField] UIFinanceSubClass m_financeSubPanel;
	//[SerializeField] UIFinanceSubClass m_financeSubPanel;
	//[SerializeField] UIFinanceSubClass m_financeSubPanel;


	[SerializeField] Button m_financeSubBtn;
	[SerializeField] Button m_financeSavingBtn;
	[SerializeField] Button m_financeLoanBtn;
	[SerializeField] Button m_financeStockBtn;

	void Awake(){
		m_financeSubBtn.onClick.AddListener (new UnityAction (financeBtnEvents));
	}

	public void initFinancePanel(){
		gameObject.SetActive (true);
		financeBtnEvents ();


	}


	private void financeBtnEvents(){
		m_financeSubPanel.gameObject.SetActive (true);
	}

	protected override void OnDisable (){
		base.OnDisable ();
	}






}


