//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.36373
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using UnityEngine;
using UnityEngine.UI;

public class UIFinanceSubClass : MonoBehaviour
{
	[SerializeField] Text[] m_pastTexts;
	[SerializeField] Text[] m_nowTexts;

	Coroutine coroutine_view = null;

	void OnEnable(){
		coroutine_view = StartCoroutine (panelViewCoroutine ());
	}

	IEnumerator panelViewCoroutine(){
		while (gameObject.activeSelf) {
			//재정 화면 데이터 갱신

			int pastMonth = AccountClass.GetInstance.financeAccount.pastIndex(0);

			if(pastMonth == 0)
				m_pastTexts[0].text = string.Format("-월");
			else
				m_pastTexts[0].text = string.Format("{0}월", pastMonth);

			m_nowTexts[0].text = string.Format("{0}월", AccountClass.GetInstance.financeAccount.nowIndex(0));

//			Debug.Log("length : " +  AccountClass.GetInstance.financeAccount.length);
			for(int i = 1; i < AccountClass.GetInstance.financeAccount.length ; i++){

				int nowValue = AccountClass.GetInstance.financeAccount.nowIndex(i);
				int pastValue = AccountClass.GetInstance.financeAccount.pastIndex(i);


				if(pastValue == 0)
					m_pastTexts[i].text = string.Format("-");
				else
					m_pastTexts[i].text = string.Format("{0:#,##0}", pastValue);

				if(nowValue == 0)
					m_nowTexts[i].text = string.Format("-");
				else
					m_nowTexts[i].text = string.Format("{0:#,##0}", nowValue);
			}
//			m_pastTexts[m_pastTexts.Length - 1].text = string.Format("{0:#,##0}", AccountClass.GetInstance.financeAccount.pastTotalValue);
//			m_nowTexts[m_nowTexts.Length - 1].text = string.Format("{0:#,##0}", AccountClass.GetInstance.financeAccount.nowTotalValue);

			yield return new WaitForSeconds(0.1f);
		}
		coroutine_view = null;
	}


	void OnDisable(){

		if (coroutine_view != null)
			StopCoroutine (coroutine_view);

		coroutine_view = null;
	}
}


