//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.36373
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using UnityEngine;
using UnityEngine.UI;

public class UILoadClass : MonoBehaviour
{



	[SerializeField] Slider m_loadBar;
	[SerializeField] Text m_loadPercentText;
	[SerializeField] Text m_loadContentsText;



	void Start(){


		//isLoad = PlayerPrefs.GetInt ("isLoad", 0);

		//Debug.Log ("isLoad : " + isLoad);



		StartCoroutine (loadSceneCoroutine());


	}


	/// <summary>
	/// 게임 화면으로 이동
	/// </summary>
	/// <returns>The scene coroutine.</returns>
	IEnumerator loadSceneCoroutine(){
		
		PlayerPrefs.DeleteKey ("isLoad");

		AsyncOperation loadSceneAsync = Application.LoadLevelAsync (2);
//		AccountClass.GetInstance.initInstance ();


		while (!loadSceneAsync.isDone) {
			Debug.Log("load Scene " + loadSceneAsync.progress);
			m_loadPercentText.text = string.Format("{0:f0}%", loadSceneAsync.progress * 100f);
			m_loadBar.value = loadSceneAsync.progress;
			yield return null;
		}
	}

	/// <summary>
	/// 에셋 번들 다운로드 - 가장 처음 시작
	/// </summary>
	/// <returns>The and caching.</returns>
//	IEnumerator DownloadAndCaching(){
//		//isLoad = true;
//
//		PlayerPrefs.SetInt ("isLoad", 1);
//
//
//
//
//
//	}


	//플레이어 데이터 가져오기


//	private void gameStart(){
//		Application.LoadLevel (2);
//	}

}


