//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.36373
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using UnityEngine.UI;
using UnityEngine;
using UnityEngine.EventSystems;
public class UINumberBtnClass : MonoBehaviour, IPointerClickHandler
{

	UIManagementClass m_parent;

	public bool isOn{ get { return GetComponent<Toggle> ().isOn; } set { GetComponent<Toggle> ().isOn = value; } }

	public void setParent (UIManagementClass parent, ToggleGroup group, int indexText){
		m_parent = parent;
		GetComponentInChildren<Text>().text = string.Format("{0}", indexText);
		GetComponent<Toggle>().group = group;

//		GetComponent<Toggle>().OnPointerClick(new PointerEventData( OnValueChanged()));
	}


	public void OnPointerClick(PointerEventData point){
		UIMadiatorClass.UIEffectSoundPlayer (TYPE_AUDIO.NONE);
		OnValueChanged ();
	}

	//클릭시 바뀜
	private void OnValueChanged(){

			//		foreach (Toggle subBtn in m_numberBtnList) {
			//			subBtn.isOn = false;
			//		}
			//		m_notUseToggle.isOn = false;
		m_parent.indexBtnClicked (int.Parse(GetComponentInChildren<Text>().text) - 1);
	}
}

