//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34209
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.Events;

public class UIProductClass : MonoBehaviour
{
	[SerializeField] Text m_waterText;
	[SerializeField] Text m_bottleText;
	[SerializeField] Text m_customerText;
	
	[SerializeField] RectTransform m_waterGraph;
	[SerializeField] RectTransform m_bottleGraph;
	[SerializeField] RectTransform m_customerGraph;
	
	void Update () {
		uiDataView();
	}
	
	private void uiDataView(){
		m_waterText.text = PrepClass.literCalculate(AccountClass.GetInstance.water);
		m_bottleText.text = AccountClass.GetInstance.bottle.ToString ();
		m_customerText.text = AccountClass.GetInstance.customer.ToString ();


		m_waterGraph.localScale = new Vector2 (AccountClass.GetInstance.getWaterPercent (), 1f);
		m_bottleGraph.localScale = new Vector2 (AccountClass.GetInstance.getBottlePercent (), 1f);
		m_customerGraph.localScale = new Vector2 (AccountClass.GetInstance.getCustomerPercent (), 1f);
	}

}


