//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34209
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class UIReputationClass : UIObjectClass
{
	readonly string[] s_list = {"어린이", "청소년", "성인", "중년", "노년"};

	[SerializeField] UIReputationElementClass m_reputationElement;
	[SerializeField] GameObject m_viewPanel;

	List<UIReputationElementClass> m_repList = new List<UIReputationElementClass> ();

	ReputationAccountClass m_reputation;

	bool m_isView = false;

	protected override void Start(){
		base.Start ();
//		m_reputation = AccountClass.GetInstance.reputation;
		int length = Enum.GetNames (typeof(TYPE_CUSTOMER)).Length;
		for(int i = 0; i < length; i++){
			UIReputationElementClass sumPanel = (UIReputationElementClass)Instantiate(m_reputationElement);
			sumPanel.setNameText(s_list[i]);
			sumPanel.gameObject.transform.parent = m_viewPanel.transform;
			m_repList.Add(sumPanel);
		}
	}

	protected override void OnEnable(){
		//코루틴 열어서 만들어진 리스트에 데이터 삽입 계속하기
		base.OnEnable ();
		StartCoroutine (panelViewRun ());
	}

	IEnumerator panelViewRun(){
		m_isView = true;
		while (m_isView) {
			for(int i = 0; i < m_repList.Count; i++){
				Debug.Log("set");
				m_repList[i].setPercentText(AccountClass.GetInstance.reputationAccount[i]);
			}
			yield return null;
		}
	}

	protected override void OnDisable(){
		//코루틴 끝내기
		m_isView = false;
		base.OnDisable ();
	}


	public void viewPanelClose(){
		panelClose ();
	}


}


