//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34209
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;
public class UIReputationElementClass : MonoBehaviour
{
	[SerializeField] Text m_nameText;
	[SerializeField] RectTransform m_graphBar;
	[SerializeField] Text m_percentText;

	public void setNameText(string name){
		m_nameText.text = name;
	}

	private void setGraphBar(float percent){
		m_graphBar.localScale = new Vector3 (percent, 1f);
	}

	public void setPercentText(float percent){
		m_percentText.text  = string.Format("{0:f0}%", percent * 100f);
		setGraphBar (percent);
	}

}


