//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34209
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using UnityEngine;
using UnityEngine.UI;
public class UIReputationSummaryClass : MonoBehaviour
{
	[SerializeField] Text m_reputationText;
	[SerializeField] Image m_reputationIconImage;

	ReputationAccountClass m_reputation;


	void Start(){
		m_reputation = AccountClass.GetInstance.reputationAccount;
		StartCoroutine (reputationSummaryRun ());

	}

	IEnumerator reputationSummaryRun(){
		while (true) {



			m_reputationText.text = string.Format("{0:f0}%", m_reputation.averageReputation() * 100f);



			yield return null;
		}
	}


	public void reputationClicked(){
		UIMadiatorClass.setReputationPanelView ();
	}


}


