//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34209
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public enum TYPE_RESEARCH{NONE, RUN, WAIT}

public class ResearchClass
{
	Sprite m_sprite;
	string m_key;
	string m_name;
	string m_contents;
	int m_product;
	int m_cost;
	string[] m_children;

	int m_runproduct = 0;

	TYPE_RESEARCH m_isResearch;

	public Sprite sprite{ get { return m_sprite; } }
	public string key{ get { return m_key; } }
	public string name{ get { return m_name; } }
	public int product{ get { return m_product - AccountClass.GetInstance.researchAccount.getReducedResearchCount(m_product); } }
	public int pinecola{ get { return (m_product > 99) ? m_product / 100 : 1; } }
	public int cost{ get { return m_cost;} }
	public string contents{ get { return m_contents; } }
	public string[] children{ get { return m_children; } }
	public TYPE_RESEARCH isResearch{ get { return m_isResearch; } }

	public ResearchClass ()
	{
	}

	public void setWaitResearch(){
		m_isResearch = TYPE_RESEARCH.WAIT;
	}

	public void setNoneResearch(){
		m_isResearch = TYPE_RESEARCH.NONE;
	}

	public void setRunResearch(){
		m_isResearch = TYPE_RESEARCH.RUN;
	}


	public ResearchClass(Sprite sprite, string key, string name, string contents, int product, int cost, string[] children){
		m_sprite = sprite;
		m_key = key;
		m_name = name;
		m_contents = contents;
		m_product = product;
		m_cost = cost;
		m_children = (string[])children.Clone ();
	}

	/// <summary>
	/// 연구량 추가
	/// </summary>
	/// <returns><c>true</c>, if product was added, <c>false</c> otherwise.</returns>
	/// <param name="count">Count.</param>
//	public bool addProduct(int count){
//
//		m_runproduct += count;
//		if(m_runproduct >= m_product){
//			return true;
//		}
//		return false;
//	}

	/// <summary>
	/// 연구량 비율
	/// </summary>
	/// <returns>The ratio.</returns>
	public float productRatio(){
		return PrepClass.ratioCalculate((float)m_runproduct, (float)m_product);
	}

}


